export const vehicleModels = {
  Abarth: ['500', '595', '695'], Acura: ['Integra', 'MDX', 'RDX', 'TLX'],
  'Alfa Romeo': ['Giulia', 'Stelvio', 'Tonale'], 'Aston Martin': ['DB12', 'DBX', 'Vantage'],
  Audi: ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q3', 'Q5', 'Q5 Premium Plus', 'Q7', 'Q8', 'e-tron'],
  Bentley: ['Bentayga', 'Continental GT', 'Flying Spur'],
  BMW: ['2 Series', '3 Series', '4 Series', '5 Series', '7 Series', 'M2', 'M3', 'M4 Competition', 'M5', 'X1', 'X3', 'X5', 'X6', 'X7', 'i4', 'i5', 'i7', 'iX'],
  Bugatti: ['Chiron', 'Divo', 'Mistral', 'Tourbillon'], Buick: ['Enclave', 'Encore', 'Envision'],
  BYD: ['Atto 3', 'Dolphin', 'Han', 'Seal', 'Song Plus', 'Tang'],
  Cadillac: ['CT4', 'CT5', 'Escalade', 'Lyriq', 'XT4', 'XT5', 'XT6'],
  Changan: ['Alsvin', 'CS35 Plus', 'CS55 Plus', 'CS75 Plus', 'UNI-K', 'UNI-T'],
  Chery: ['Arrizo 5', 'Arrizo 8', 'Tiggo 4', 'Tiggo 7', 'Tiggo 8'],
  Chevrolet: ['Blazer', 'Camaro', 'Captiva', 'Corvette', 'Equinox', 'Silverado', 'Suburban', 'Tahoe', 'Traverse'],
  Chrysler: ['300', 'Pacifica', 'Voyager'], Citroen: ['C3', 'C4', 'C5 Aircross', 'Berlingo'],
  Cupra: ['Ateca', 'Born', 'Formentor', 'Leon'], Dacia: ['Duster', 'Jogger', 'Logan', 'Sandero'],
  Daewoo: ['Lanos', 'Leganza', 'Matiz', 'Nubira'], Daihatsu: ['Copen', 'Mira', 'Rocky', 'Terios'],
  Dodge: ['Challenger', 'Charger', 'Durango', 'Hornet'], Dongfeng: ['Mage', 'Rich 6', 'Shine'],
  'DS Automobiles': ['DS 3', 'DS 4', 'DS 7', 'DS 9'], Ferrari: ['296', '812', 'Purosangue', 'Roma', 'SF90'],
  Fiat: ['500', '500X', 'Doblo', 'Panda', 'Tipo'], Fisker: ['Karma', 'Ocean'],
  Ford: ['Bronco', 'Edge', 'Escape', 'Expedition', 'Explorer', 'F-150', 'Mustang', 'Ranger'],
  Geely: ['Coolray', 'Emgrand', 'Monjaro', 'Okavango', 'Tugella'],
  Genesis: ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80'],
  GMC: ['Acadia', 'Canyon', 'Sierra', 'Terrain', 'Yukon'], 'Great Wall': ['Cannon', 'Poer', 'Wingle'],
  Haval: ['Dargo', 'H6', 'H9', 'Jolion'], Honda: ['Accord', 'Civic', 'CR-V', 'HR-V', 'Pilot'],
  Hongqi: ['E-HS9', 'H5', 'H9', 'HS5'], Hummer: ['H1', 'H2', 'H3', 'EV'],
  Hyundai: ['Accent', 'Creta', 'Elantra', 'Ioniq 5', 'Kona', 'Palisade', 'Santa Fe', 'Sonata', 'Tucson'],
  Infiniti: ['Q50', 'Q60', 'QX50', 'QX60', 'QX80'], Isuzu: ['D-Max', 'MU-X'],
  Jaguar: ['E-Pace', 'F-Pace', 'F-Type', 'I-Pace', 'XE', 'XF'],
  Jeep: ['Cherokee', 'Compass', 'Gladiator', 'Grand Cherokee', 'Renegade', 'Wrangler'],
  Jetour: ['Dashing', 'T1', 'T2', 'X70', 'X90'],
  Kia: ['Carnival', 'EV6', 'K5', 'Rio', 'Seltos', 'Sorento', 'Sportage', 'Telluride'],
  Koenigsegg: ['CC850', 'Gemera', 'Jesko', 'Regera'], Lamborghini: ['Aventador', 'Huracan', 'Revuelto', 'Urus'],
  Lancia: ['Delta', 'Thema', 'Ypsilon'],
  'Land Rover': ['Defender', 'Discovery', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar'],
  Lexus: ['ES', 'GX', 'IS', 'LC', 'LM', 'LS', 'LX', 'NX', 'RX', 'UX'],
  Lincoln: ['Aviator', 'Corsair', 'Nautilus', 'Navigator'], Lotus: ['Elise', 'Eletre', 'Emira', 'Evija'],
  Lucid: ['Air', 'Gravity'], Maserati: ['Ghibli', 'GranTurismo', 'Grecale', 'Levante', 'MC20', 'Quattroporte'],
  Mazda: ['CX-3', 'CX-30', 'CX-5', 'CX-60', 'CX-90', 'Mazda3', 'Mazda6', 'MX-5'],
  McLaren: ['570S', '720S', '750S', 'Artura', 'GT'],
  'Mercedes-Benz': ['A-Class', 'C-Class', 'C300', 'CLA', 'E-Class', 'G-Class', 'GLA', 'GLC', 'GLE', 'GLS', 'S-Class', 'AMG GT', 'EQA', 'EQE', 'EQS'],
  MG: ['MG 3', 'MG 4', 'MG 5', 'MG 7', 'HS', 'RX5', 'ZS'], MINI: ['Clubman', 'Convertible', 'Cooper', 'Countryman'],
  Mitsubishi: ['ASX', 'Attrage', 'Eclipse Cross', 'L200', 'Montero', 'Outlander', 'Pajero'],
  NIO: ['EC6', 'ES6', 'ES8', 'ET5', 'ET7'],
  Nissan: ['Altima', 'Armada', 'Kicks', 'Patrol', 'Pathfinder', 'Rogue', 'Sentra', 'Sunny', 'X-Trail', 'Z'],
  Opel: ['Astra', 'Combo', 'Corsa', 'Crossland', 'Grandland', 'Insignia'], Pagani: ['Huayra', 'Utopia', 'Zonda'],
  Peugeot: ['208', '308', '508', '2008', '3008', '5008', 'Partner'], Polestar: ['Polestar 2', 'Polestar 3', 'Polestar 4'],
  Porsche: ['718', '911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
  Proton: ['Exora', 'Iriz', 'Persona', 'Saga', 'X50', 'X70'], RAM: ['1500', '2500', '3500', 'ProMaster'],
  Renault: ['Arkana', 'Captur', 'Clio', 'Duster', 'Koleos', 'Megane', 'Symbol'],
  Rimac: ['Concept One', 'Nevera'], Rivian: ['R1S', 'R1T'],
  'Rolls-Royce': ['Cullinan', 'Dawn', 'Ghost', 'Phantom', 'Spectre', 'Wraith'],
  Saab: ['9-3', '9-5', '900', '9000'], SEAT: ['Arona', 'Ateca', 'Ibiza', 'Leon', 'Tarraco'],
  Skoda: ['Fabia', 'Kamiq', 'Karoq', 'Kodiaq', 'Octavia', 'Superb'], Smart: ['#1', '#3', 'ForFour', 'ForTwo'],
  'KGM (SsangYong)': ['Korando', 'Musso', 'Rexton', 'Tivoli', 'Torres'],
  Subaru: ['BRZ', 'Crosstrek', 'Forester', 'Impreza', 'Legacy', 'Outback', 'WRX'],
  Suzuki: ['Baleno', 'Ciaz', 'Jimny', 'Swift', 'Vitara'], Tata: ['Harrier', 'Nexon', 'Safari', 'Tiago'],
  Tesla: ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y'],
  Toyota: ['Camry', 'Corolla', 'Fortuner', 'Highlander', 'Hilux', 'Land Cruiser', 'Prado', 'RAV4', 'Supra', 'Yaris'],
  VinFast: ['VF 5', 'VF 6', 'VF 7', 'VF 8', 'VF 9'],
  Volkswagen: ['Amarok', 'Golf', 'ID.4', 'Jetta', 'Passat', 'Taos', 'Tiguan', 'Touareg'],
  Volvo: ['C40', 'EX30', 'EX90', 'S60', 'S90', 'V60', 'XC40', 'XC60', 'XC90'],
  XPeng: ['G6', 'G9', 'P5', 'P7'], Zeekr: ['001', '007', '009', 'X'],
};

export const vehicleMakes = Object.keys(vehicleModels).sort((left, right) => left.localeCompare(right));
export const drivetrainOptions = ['FWD', 'RWD', 'AWD', '4WD'];
export const transmissionOptions = ['Automatic', 'Manual', 'CVT', 'Dual-clutch', 'Automated manual'];
